var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/cookie-policy/page.js")
R.c("server/chunks/ssr/_95206db6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0c1ef9cf._.js")
R.c("server/chunks/ssr/_7e7a80cf._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3ba03da5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/[root-of-the-server]__709fb98b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__c6122a4e._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_cookie-policy_page_actions_14b1ec46.js")
R.m(6980)
module.exports=R.m(6980).exports
